name: gsy_flutter_demo
description: A new Flutter application by gsy

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.1.0+10

environment:
  sdk: '>=3.0.0 <4.0.0'

deferred-components:
  - name: crane
    libraries:
      - package:gsy_flutter_demo/widget/animation/anim_bubble_gum.dart
      - package:gsy_flutter_demo/widget/animation/anim_button/anim_button_demo_page.dart
      - package:gsy_flutter_demo/widget/animation/anim_progress_img_demo_page.dart
      - package:gsy_flutter_demo/widget/animation/anim_scan_demo_page.dart
      - package:gsy_flutter_demo/widget/animation/anim_text_demo_page.dart
      - package:gsy_flutter_demo/widget/animation/arc_seek_bar_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/bottom_anim_nav_page.dart
      - package:gsy_flutter_demo/widget/canvas/canvas_click_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/chat_list_scroll_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/chat_list_scroll_demo_page_2.dart
      - package:gsy_flutter_demo/widget/basic/color_progress_demo_page.dart
      - package:gsy_flutter_demo/widget/canvas/drag_img_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/gradient_text_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/index_stack_drag_card_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/index_stack_drag_card_demo_page2.dart
      - package:gsy_flutter_demo/widget/scroll/link_sliver/link_sliver_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/rich_text_demo_page2.dart
      - package:gsy_flutter_demo/widget/basic/route_demo_page.dart
      - package:gsy_flutter_demo/widget/scroll/scroll_inner_content_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/align_demo_page.dart
      - package:gsy_flutter_demo/widget/animation/anim_bg_demo_page.dart
      - package:gsy_flutter_demo/widget/animation/anim_tip_demo_page.dart
      - package:gsy_flutter_demo/widget/animation/anima_demo_page.dart
      - package:gsy_flutter_demo/widget/animation/anima_demo_page2.dart
      - package:gsy_flutter_demo/widget/animation/anima_demo_page4.dart
      - package:gsy_flutter_demo/widget/animation/anima_demo_page5.dart
      - package:gsy_flutter_demo/widget/animation/animation_container_demo_page.dart
      - package:gsy_flutter_demo/widget/canvas/blur_demo_page.dart
      - package:gsy_flutter_demo/widget/animation/book_page/book_page.dart
      - package:gsy_flutter_demo/widget/basic/bubble/bubble_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/card_item_page.dart
      - package:gsy_flutter_demo/widget/basic/clip_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/cloud/cloud_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/controller_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/custom_multi_render_demo_page.dart
      - package:gsy_flutter_demo/widget/scroll/custom_pull/refresh_demo_page3.dart
      - package:gsy_flutter_demo/widget/scroll/custom_sliver/scroll_header_demo_page.dart
      - package:gsy_flutter_demo/widget/scroll/custom_viewport/custom_viewport_page.dart
      - package:gsy_flutter_demo/widget/basic/drop_select_menu/drop_select_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/floating_touch_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/honor_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/input_bottom_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/keyboard_demo_page.dart
      - package:gsy_flutter_demo/widget/scroll/list_anim/list_anim_demo_page.dart
      - package:gsy_flutter_demo/widget/scroll/list_anim_2/list_anim_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/overflow_image_page.dart
      - package:gsy_flutter_demo/widget/animation/particle/particle_page.dart
      - package:gsy_flutter_demo/widget/basic/positioned_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/refresh_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/refresh_demo_page2.dart
      - package:gsy_flutter_demo/widget/basic/rich_text_demo_page.dart
      - package:gsy_flutter_demo/widget/scroll/scroll_listener_demo_page.dart
      - package:gsy_flutter_demo/widget/scroll/scroll_to_index_demo_page.dart
      - package:gsy_flutter_demo/widget/scroll/scroll_to_index_demo_page2.dart
      - package:gsy_flutter_demo/widget/scroll/slider_verify_page.dart
      - package:gsy_flutter_demo/widget/scroll/sliver_list_demo_page.dart
      - package:gsy_flutter_demo/widget/scroll/sliver_stick_demo_page.dart
      - package:gsy_flutter_demo/widget/scroll/sliver_tab_demo_page.dart
      - package:gsy_flutter_demo/widget/scroll/sliver_tab_demo_page2.dart
      - package:gsy_flutter_demo/widget/scroll/sliver_tab/sliver_tab_demo_page3.dart
      - package:gsy_flutter_demo/widget/basic/statusbar_demo_page.dart
      - package:gsy_flutter_demo/widget/scroll/stick/stick_demo_page.dart
      - package:gsy_flutter_demo/widget/scroll/stick/stick_demo_page2.dart
      - package:gsy_flutter_demo/widget/scroll/stick_sliver_list_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/tag_demo_page.dart
      - package:gsy_flutter_demo/widget/canvas/matrix_custom_painter_page.dart
      - package:gsy_flutter_demo/widget/basic/text_line_height_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/text_size_demo_page.dart
      - package:gsy_flutter_demo/widget/canvas/tick_click_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/transform_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/verification_code_input_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/verification_code_input_demo_page2.dart
      - package:gsy_flutter_demo/widget/scroll/viewpager_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/wrap_content_page.dart
      - package:gsy_flutter_demo/widget/canvas/shader_canvas_demo_page.dart
      - package:gsy_flutter_demo/widget/animation/anim_switch_layout_demo_page.dart
      - package:gsy_flutter_demo/widget/scroll/vp_list_demo_page.dart
      - package:gsy_flutter_demo/widget/visual/card_perspective_demo_page.dart
      - package:gsy_flutter_demo/widget/visual/card_3d_demo_page.dart
      - package:gsy_flutter_demo/widget/visual/card_real_3d_demo_page.dart
      - package:gsy_flutter_demo/widget/visual/anim_juejin_logo_demo_page.dart
      - package:gsy_flutter_demo/widget/visual/dash_3d_demo_page.dart
      - package:gsy_flutter_demo/widget/basic/png_shadow_demo_page.dart
      - package:gsy_flutter_demo/widget/canvas/transform_canvas_demo_page.dart
      - package:gsy_flutter_demo/widget/visual/juejin_3d_logo_demo_page.dart
      - package:gsy_flutter_demo/widget/visual/juejin_3d_box_logo_demo_page.dart
      - package:gsy_flutter_demo/widget/scroll/link_scroll_page.dart
      - package:gsy_flutter_demo/widget/canvas/glass_demo_page.dart
      - package:gsy_flutter_demo/widget/canvas/liquid_glass_demo.dart
      - package:gsy_flutter_demo/widget/canvas/liquid_glass_demo2.dart
      - package:gsy_flutter_demo/widget/animation/attractor_page.dart
      - package:gsy_flutter_demo/widget/animation/fibonacci_sphere_page.dart
      - package:gsy_flutter_demo/widget/visual/galaxy_scene_page.dart
      - package:gsy_flutter_demo/widget/animation/neon_slider_page.dart
      - package:gsy_flutter_demo/widget/canvas/radial_lines_page.dart
      - package:gsy_flutter_demo/widget/animation/boom_particle_page.dart
      - package:gsy_flutter_demo/widget/visual/black_hole_simulation_page.dart
      - package:gsy_flutter_demo/widget/visual/stream_taichi_page.dart
      - package:gsy_flutter_demo/widget/visual/black_hole_page.dart
      - package:gsy_flutter_demo/widget/visual/taichi_page.dart
      - package:gsy_flutter_demo/widget/basic/akaza_page.dart
      - package:gsy_flutter_demo/widget/scroll/tornado_scroll_demo.dart
      - package:gsy_flutter_demo/widget/animation/combined_scene_page.dart
      - package:gsy_flutter_demo/widget/visual/notion_qrcode_page.dart
      - package:gsy_flutter_demo/widget/visual/spatial_grid_page.dart
      - package:gsy_flutter_demo/widget/scroll/shock_wave_chat_page.dart
      - package:gsy_flutter_demo/widget/visual/mosaic_scanner_page.dart
      - package:gsy_flutter_demo/widget/visual/koi_fish_animation.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^1.0.3
  scroll_to_index: 3.0.1
  another_transformer_page_view: 2.0.0
  simple_animations: 5.0.2
  supercharged: 2.1.1
  matrix_gesture_detector: 0.2.0-nullsafety.1
  flutter_swiper_view: 1.1.8
  animated_text_kit: 4.2.1
  window_location_href: 1.0.0
  rive: 0.13.20
  animations: 2.0.4
  flutter_animate: ^1.0.0
  polygon: ^0.1.0
  qr: ^3.0.1
  zflutter:
    git:
      url: https://github.com/CarGuo/zflutter.git
      ref: 3f5e569ba96f4c94a5847aad96617f273d88629d
      path: zflutter/


  vector_math: any
dev_dependencies:
  build_runner: ^2.0.5
  build_web_compilers: ^3.0.0
  flutter_lints: 3.0.2
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  shaders:
    - shaders/liquid_glass.frag
    - shaders/liquid_glass2.frag
    - shaders/shockwave.frag
    - shaders/elastic.frag
    - shaders/mosaic_wave.frag

  # To add assets to your application, add an assets section, like this:
  assets:
    - static/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: Canterbury
      fonts:
        - asset: assets/Canterbury.ttf

    - family: HelloStockholm
      fonts:
        - asset: assets/HelloStockholm.otf

    - family: Horizon
      fonts:
        - asset: assets/Horizon.otf

    - family: Bobbers
      fonts:
        - asset: assets/Bobbers.ttf

    - family: Agne
      fonts:
        - asset: assets/Agne.otf

    - family: bglbt
      fonts:
        - asset: assets/bglbt.ttf
